backend:
  name: github
  repo: e-paire/land-seekers
  branch: master

display_url: https://landseekers.blog
media_folder: static/images/
public_folder: content/images/

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts/"
    create: true
    delete: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - name: "slug"
        label: "Slug"
        widget: "string"
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "date"
        label: "Publish Date"
        widget: "date"
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name"]
        valueField: "name"
        required: false
      - name: "metaTitle"
        label: "Meta title"
        widget: "string"
      - name: "metaDescription"
        label: "Meta description"
        widget: "string"
      - name: "cover"
        label: "Cover"
        widget: "image"
        required: false
      - label: "Country"
        name: "country"
        widget: "relation"
        collection: "countries"
        searchFields: ["name"]
        valueField: "name"
        required: false
      - name: "body"
        label: "Body"
        widget: "markdown"
  - name: "authors"
    label: "Authors"
    folder: "content/authors/"
    create: false
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - name: "slug"
        label: "Slug"
        widget: "string"
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "cover"
        label: "Cover"
        widget: "image"
        required: false
      - name: "body"
        label: "Body"
        widget: "markdown"
  - name: "countries"
    label: "Countries"
    folder: "content/countries/"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - name: "slug"
        label: "Slug"
        widget: "string"
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "cover"
        label: "Cover"
        widget: "image"
        required: false
      - name: "body"
        label: "Body"
        widget: "markdown"
