backend:
  name: github
  repo: e-paire/land-seekers-content
  branch: master

display_url: https://landseekers.blog
media_folder: assets

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts/"
    create: true
    delete: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "date"
        label: "Publish Date"
        widget: "date"
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name"]
        valueField: "name"
        required: false
      - name: "cover"
        label: "Cover"
        widget: "image"
        required: false
      - name: "body"
        label: "Body"
        widget: "markdown"
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: []
        required: false
  - name: "authors"
    label: "Authors"
    folder: "authors/"
    create: false
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "name"
        label: "Name"
        widget: "string"
      - name: "body"
        label: "Body"
        widget: "markdown"
