backend:
  name: github
  repo: e-paire/land-seekers
  branch: master
  accept_roles:
    - admin
    - editor
publish_mode: editorial_workflow
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts/"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "date"
        label: "Publish Date"
        widget: "date"
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name"]
        valueField: "name"
      - name: "cover"
        label: "Cover"
        widget: "image"
      - name: "body"
        label: "Body"
        widget: "markdown"
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: []
  - name: "author"
    label: "Blog"
    folder: "content/authors/"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "name"
        label: "Name"
        widget: "string"
      - name: "body"
        label: "Body"
        widget: "markdown"
