backend:
  name: github
  repo: e-paire/land-seekers
  branch: master
  accept_roles:
    - admin
    - editor

media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts/"
    create: true
    delete: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "date"
        label: "Publish Date"
        widget: "date"
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name"]
        valueField: "name"
        required: false
      - name: "cover"
        label: "Cover"
        widget: "image"
        required: false
      - name: "body"
        label: "Body"
        widget: "markdown"
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: []
        required: false
  - name: "authors"
    label: "Authors"
    folder: "content/authors/"
    create: false
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "name"
        label: "Name"
        widget: "string"
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name"]
        valueField: "name"
        required: false
      - name: "cover"
        label: "Cover"
        widget: "image"
        required: false
      - name: "body"
        label: "Body"
        widget: "markdown"
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: []
        required: false
  - name: "pages"
    label: "Pages"
    folder: "content/pages/"
    create: true
    delete: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "body"
        label: "Body"
        widget: "markdown"
